### PR TITLE
Fix PotSS Garden 3 Upper Ledge logic

### PR DESCRIPTION
**Pull request by LumineonRL**
Root alone is insufficient for reaching this ledge - climb would be required too.

PotSS Garden 3 upper ledge logic

### CODE REVIEW

**Comment by BrandenEK** [comment]
Good catch

**Comment by BrandenEK** [comment]
Also, I see that you have a random blasphemous skin project - We should make that into an actual mod

**Comment by LumineonRL** [comment]
> Also, I see that you have a random blasphemous skin project - We should make that into an actual mod

Agreed! Looking into setting up the Modding API now.

**Comment by BrandenEK** [comment]
Awesome, let me know if you have any questions. 

Discord: Damocles03

**Pull request merged**
